[package]
name = "brawl_29v"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
chrono = "0.4.40"
once_cell = "1.21.3"
bytes = "1.10.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"